### ISSUE TITLE
something is wrong with the optimizer

### ISSUE THREAD

**Issue by Yongda1** [google-deepmind/ferminet#96]
I am running ferminet on my RTX5070Ti. I install the jax by the default version.
However,  I got one error,
TypeError: _broadcast_in_dim_staging_rule() missing 1 required keyword-only argument: 'sharding'

May I get some help?

Best regards
Jim

**Comment by jsspencer** [comment]
Impossible to know what the issue is without more details. Can you provide a full stack trace, the config/script you are using, and the output of `pip freeze`? Are you using folx to speed up Laplacian evaluation?

**Comment by Yongda1** [comment]
Thanks for your reply. 
config is here,
import sys

from absl import logging
from ferminet.utils import system
from ferminet import base_config
from ferminet import train

# Optional, for also printing training progress to STDOUT.
# If running a script, you can also just use the --alsologtostderr flag.
logging.get_absl_handler().python_handler.stream = sys.stdout
logging.set_verbosity(logging.INFO)

# Define H2 molecule
cfg = base_config.default()
cfg.system.electrons = (1, 1)  # (alpha electrons, beta electrons)
cfg.network.complex = True

cfg.system.molecule = [system.Atom('H', (0, 0, -1)), system.Atom('H', (0, 0, 1))]

# Set training parameters
cfg.batch_size = 4
cfg.pretrain.iterations = 0

train.train(cfg)

the detail of the error is here,
Traceback (most recent call last):
  File "/mnt/c/Users/Administrator/PycharmProjects/ferminet/configs/H2.py", line 24, in <module>
    train.train(cfg)
  File "/mnt/c/Users/Administrator/PycharmProjects/ferminet/train.py", line 785, in train
    opt_state = optimizer.init(params, subkeys, data)
  File "/root/anaconda3/envs/jaxenvA/lib/python3.12/site-packages/kfac_jax/_src/optimizer.py", line 1018, in init
    return self._init(params, rng, batch, func_state)
  File "/root/anaconda3/envs/jaxenvA/lib/python3.12/site-packages/kfac_jax/_src/utils/staging.py", line 248, in decorated
    outs = func(instance, *args)
  File "/root/anaconda3/envs/jaxenvA/lib/python3.12/site-packages/kfac_jax/_src/optimizer.py", line 986, in _init
    estimator_state=self.estimator.init(
  File "/root/anaconda3/envs/jaxenvA/lib/python3.12/site-packages/kfac_jax/_src/utils/misc.py", line 286, in wrapped
    return method(instance, *args, **kwargs)
  File "/root/anaconda3/envs/jaxenvA/lib/python3.12/site-packages/kfac_jax/_src/curvature_estimator.py", line 1183, in init
    self.finalize(func_args)
  File "/root/anaconda3/envs/jaxenvA/lib/python3.12/site-packages/kfac_jax/_src/utils/misc.py", line 259, in finalize
    self._finalize(*args, **kwargs)
  File "/root/anaconda3/envs/jaxenvA/lib/python3.12/site-packages/kfac_jax/_src/curvature_estimator.py", line 1169, in _finalize
    self._jaxpr = self._vjp(func_args, return_only_jaxpr=True)  # pytype: disable=annotation-type-mismatch  # always-use-return-annotations
  File "/root/anaconda3/envs/jaxenvA/lib/python3.12/site-packages/kfac_jax/_src/tracer.py", line 354, in wrapped_transformation
    jaxpr = ProcessedJaxpr.make_from_func(
  File "/root/anaconda3/envs/jaxenvA/lib/python3.12/site-packages/kfac_jax/_src/tracer.py", line 244, in make_from_func
    func = tgm.auto_register_tags(
  File "/root/anaconda3/envs/jaxenvA/lib/python3.12/site-packages/kfac_jax/_src/tag_graph_matcher.py", line 1567, in auto_register_tags
    graph = make_jax_graph(
  File "/root/anaconda3/envs/jaxenvA/lib/python3.12/site-packages/kfac_jax/_src/tag_graph_matcher.py", line 345, in make_jax_graph
    closed_jaxpr, out_shapes = jax.make_jaxpr(func, return_shape=True)(*func_args)
  File "/root/anaconda3/envs/jaxenvA/lib/python3.12/site-packages/kfac_jax/_src/optimizer.py", line 1568, in value_func
    out, _ = value_and_grad_func(*args, **kwargs)
  File "/mnt/c/Users/Administrator/PycharmProjects/Ab-initio-Flexible-Gaussian-Basis-Neural-Network-Quantum-Monte-Carlo/ferminet/loss.py", line 256, in total_energy_jvp
    psi_primal, psi_tangent = jax.jvp(batch_network, primals, tangents)
  File "/mnt/c/Users/Administrator/PycharmProjects/Ab-initio-Flexible-Gaussian-Basis-Neural-Network-Quantum-Monte-Carlo/ferminet/train.py", line 524, in log_network
    phase, mag = signed_network(*args, **kwargs)
  File "/mnt/c/Users/Administrator/PycharmProjects/Ab-initio-Flexible-Gaussian-Basis-Neural-Network-Quantum-Monte-Carlo/ferminet/networks.py", line 1498, in apply
    orbitals = orbitals_apply(params, pos, spins, atoms, charges)
  File "/mnt/c/Users/Administrator/PycharmProjects/Ab-initio-Flexible-Gaussian-Basis-Neural-Network-Quantum-Monte-Carlo/ferminet/networks.py", line 1189, in apply
    ae, ee, r_ae, r_ee = construct_input_features(pos, atoms, ndim=options.ndim)
  File "/mnt/c/Users/Administrator/PycharmProjects/Ab-initio-Flexible-Gaussian-Basis-Neural-Network-Quantum-Monte-Carlo/ferminet/networks.py", line 478, in construct_input_features
    jnp.linalg.norm(ee + jnp.eye(n)[..., None], axis=-1) * (1.0 - jnp.eye(n)))
  File "/root/anaconda3/envs/jaxenvA/lib/python3.12/site-packages/jax/_src/numpy/array_methods.py", line 1060, in op
    return getattr(self.aval, f"_{name}")(self, *args)
  File "/root/anaconda3/envs/jaxenvA/lib/python3.12/site-packages/jax/_src/numpy/array_methods.py", line 652, in _getitem
    return indexing.rewriting_take(self, item)
  File "/root/anaconda3/envs/jaxenvA/lib/python3.12/site-packages/jax/_src/numpy/indexing.py", line 633, in rewriting_take
    return _gather(arr, treedef, static_idx, dynamic_idx, indices_are_sorted,
  File "/root/anaconda3/envs/jaxenvA/lib/python3.12/site-packages/jax/_src/numpy/indexing.py", line 681, in _gather
    return lax.expand_dims(y, indexer.newaxis_dims)
jax._src.source_info_util.JaxStackTraceBeforeTransformation: TypeError: _broadcast_in_dim_staging_rule() missing 1 required keyword-only argument: 'sharding'

The preceding stack trace is the source of the JAX operation that, once transformed by JAX, triggered the following exception.

--------------------

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/c/Users/Administrator/PycharmProjects/ferminet/configs/H2.py", line 24, in <module>
    train.train(cfg)
  File "/mnt/c/Users/Administrator/PycharmProjects/ferminet/train.py", line 785, in train
    opt_state = optimizer.init(params, subkeys, data)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/jaxenvA/lib/python3.12/site-packages/kfac_jax/_src/optimizer.py", line 1018, in init
    return self._init(params, rng, batch, func_state)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/jaxenvA/lib/python3.12/site-packages/kfac_jax/_src/utils/staging.py", line 248, in decorated
    outs = func(instance, *args)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/jaxenvA/lib/python3.12/site-packages/kfac_jax/_src/optimizer.py", line 986, in _init
    estimator_state=self.estimator.init(
                    ^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/jaxenvA/lib/python3.12/site-packages/kfac_jax/_src/utils/misc.py", line 286, in wrapped
    return method(instance, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/jaxenvA/lib/python3.12/site-packages/kfac_jax/_src/curvature_estimator.py", line 1183, in init
    self.finalize(func_args)
  File "/root/anaconda3/envs/jaxenvA/lib/python3.12/site-packages/kfac_jax/_src/utils/misc.py", line 259, in finalize
    self._finalize(*args, **kwargs)
  File "/root/anaconda3/envs/jaxenvA/lib/python3.12/site-packages/kfac_jax/_src/curvature_estimator.py", line 1169, in _finalize
    self._jaxpr = self._vjp(func_args, return_only_jaxpr=True)  # pytype: disable=annotation-type-mismatch  # always-use-return-annotations
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/jaxenvA/lib/python3.12/site-packages/kfac_jax/_src/tracer.py", line 354, in wrapped_transformation
    jaxpr = ProcessedJaxpr.make_from_func(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/jaxenvA/lib/python3.12/site-packages/kfac_jax/_src/tracer.py", line 250, in make_from_func
    typed_jaxpr = jax.make_jaxpr(func)(*func_args)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/jaxenvA/lib/python3.12/site-packages/kfac_jax/_src/tag_graph_matcher.py", line 1294, in __call__
    flat_output = self._flat_func(*flat_args)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: _broadcast_in_dim_staging_rule() missing 1 required keyword-only argument: 'sharding'
--------------------

Process finished with exit code 1

**Comment by KingDamLiu** [comment]
I had a similar problem with folx<0.2.15 (didn't have the problem with folx=0.2.15)：
  File "/home/gengzi/deepwavefunction/ferminet/ferminet/loss.py", line 240, in total_energy_jvp
    loss, aux_data = total_energy(params, key, data)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gengzi/deepwavefunction/ferminet/ferminet/loss.py", line 224, in total_energy
    e_l, e_l_mat = batch_local_energy(params, keys, data)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gengzi/deepwavefunction/ferminet/ferminet/hamiltonian.py", line 450, in _e_l
    kinetic = ke(params, data)
              ^^^^^^^^^^^^^^^^
  File "/home/gengzi/deepwavefunction/ferminet/ferminet/hamiltonian.py", line 145, in _lapl_over_f
    output = f_wrapped(data.positions)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gengzi/.conda/envs/ferminet_new/lib/python3.11/site-packages/folx/interpreter.py", line 295, in wrapped
    out = eval_jaxpr_with_forward_laplacian(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gengzi/.conda/envs/ferminet_new/lib/python3.11/site-packages/folx/interpreter.py", line 212, in eval_jaxpr_with_forward_laplacian
    raise e
  File "/home/gengzi/.conda/envs/ferminet_new/lib/python3.11/site-packages/folx/interpreter.py", line 208, in eval_jaxpr_with_forward_laplacian
    outvals = eval_laplacian(eqn, invals)
^^^^^^^
  File "/home/gengzi/.conda/envs/ferminet_new/lib/python3.11/site-packages/folx/interpreter.py", line 167, in eval_laplacian
    return fn(
           ^^^
  File "/home/gengzi/.conda/envs/ferminet_new/lib/python3.11/site-packages/folx/wrapper.py", line 122, in new_fn
    y, grad_y, lapl_y = lapl_fns.jvp(laplace_args, kwargs)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gengzi/.conda/envs/ferminet_new/lib/python3.11/site-packages/folx/jvp.py", line 576, in jvp
    return parallel_jvp(args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gengzi/.conda/envs/ferminet_new/lib/python3.11/site-packages/folx/jvp.py", line 501, in parallel_jvp
    return sparse_index_jvp(
           ^^^^^^^^^^^^^^^^^
  File "/home/gengzi/.conda/envs/ferminet_new/lib/python3.11/site-packages/folx/jvp.py", line 310, in sparse_index_jvp
    return dense_jvp(merged_fwd, laplace_args, flags=flags, in_axes=in_axes)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gengzi/.conda/envs/ferminet_new/lib/python3.11/site-packages/folx/jvp.py", line 478, in dense_jvp
    y, grad_y, lapl_y = dense_split_jvp(fwd, laplace_args)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gengzi/.conda/envs/ferminet_new/lib/python3.11/site-packages/folx/jvp.py", line 445, in dense_split_jvp
    y, jvp = jax.linearize(fwd, *laplace_args.x)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gengzi/.conda/envs/ferminet_new/lib/python3.11/site-packages/folx/jvp.py", line 493, in merged_fwd
    return fwd(*merge(args, extra_args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: reshape() got an unexpected keyword argument 'sharding'

However, using folx 0.2.15 there is a convergence anomaly where the average energy is significantly lower than the reference energy by hundreds of mha,and the convergence is very unstable.

**Comment by jsspencer** [comment]
> I am using jax 0.5.3 version. kfac_jax 0.0.6 version. Python 3.12 version.

You are using a very new version of jax and a quite old version of kfac_jax. (And you must be using an old version of ferminet, as ferminet@HEAD does not work with kfac_jax 0.0.6 due to (for example) the use of  `kfac_jax.LayerVjpData`.) Please try upgrading to a newer version of kfac_jax.

**Comment by jsspencer** [comment]
> However, using folx 0.2.15 there is a convergence anomaly where the average energy is significantly lower than the reference energy by hundreds of mha,and the convergence is very unstable.

I have not seen this -- can you give an example of such a system please?  (folx 0.2.14 should work with jax < 0.5.1, as [this commit](https://github.com/jax-ml/jax/commit/1a62df1ac0e89b5eaf243097ea3f48d97264d221) introduces an API change.)

**Comment by Yongda1** [comment]
Thanks. However, the new kfac_jax is 0.0.6. I found the following line in the src directory.
`__version__ = "0.0.6"`
Ok, I will try to download the current ferminet.

Best regards
Jim

**Comment by Yongda1** [comment]
Excuse me, I download the current ferminet version. I got this,
```
Traceback (most recent call last):
  File "/mnt/c/Users/Administrator/Desktop/Fermi-net/24-3-2025/ferminet-main/ferminet-main/H2.py", line 6, in <module>
    from ferminet import train
  File "/mnt/c/Users/Administrator/Desktop/Fermi-net/24-3-2025/ferminet-main/ferminet-main/ferminet/train.py", line 25, in <module>
    from ferminet import checkpoint
  File "/mnt/c/Users/Administrator/Desktop/Fermi-net/24-3-2025/ferminet-main/ferminet-main/ferminet/checkpoint.py", line 24, in <module>
    from ferminet import networks
  File "/mnt/c/Users/Administrator/Desktop/Fermi-net/24-3-2025/ferminet-main/ferminet-main/ferminet/networks.py", line 21, in <module>
    from ferminet import envelopes
  File "/mnt/c/Users/Administrator/Desktop/Fermi-net/24-3-2025/ferminet-main/ferminet-main/ferminet/envelopes.py", line 21, in <module>
    from ferminet import curvature_tags_and_blocks
  File "/mnt/c/Users/Administrator/Desktop/Fermi-net/24-3-2025/ferminet-main/ferminet-main/ferminet/curvature_tags_and_blocks.py", line 54, in <module>
    class RepeatedDenseBlock(kfac_jax.DenseTwoKroneckerFactored):
  File "/mnt/c/Users/Administrator/Desktop/Fermi-net/24-3-2025/ferminet-main/ferminet-main/ferminet/curvature_tags_and_blocks.py", line 64, in RepeatedDenseBlock
    estimation_data: kfac_jax.LayerVjpData[Array],
                     ^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'kfac_jax' has no attribute 'LayerVjpData'
ERROR conda.cli.main_run:execute(125): `conda run python /mnt/c/Users/Administrator/Desktop/Fermi-net/24-3-2025/ferminet-main/ferminet-main/H2.py` failed. (See above for error)
```
And the latest version  that I can find is 0.0.6. 
![Image](https://github.com/user-attachments/assets/b72be7af-9b74-406c-a067-d91338f652fc)

Best regards
Yongda Huang

**Comment by jsspencer** [comment]
kfac_jax hasn't made a tagged release for a while but the latest development commit is compatible with recent releases of jax. You can either install a development version of kfac_jax (using, eg `pip install 'kfac_jax @ git+https://github.com/deepmind/kfac-jax'`) or use an older version of jax. The former is done in ferminet's setup.py

**Comment by KingDamLiu** [comment]
Here is my calculation code. I conducted tests on two systems, H₂O and BH, respectively. The test environment was Python 3.11, JAX 0.5.3, and folx = 0.2.15. When using folx, after 200,000 iterations, for the BH system, the average energy of the last 1000 steps was -25.328784883 Ha, and the reference energy was -25.289 Ha. Moreover, the convergence fluctuation (E_std = 0.1604 Ha) was significantly larger than that without folx (E_std = 0.0066 Ha). For the H₂O system (E = -76.5333 Ha), the reference energy was -76.438 Ha, and the convergence fluctuation (E_std = 0.0433 Ha) was also significantly larger than that without folx (E_std = 0.00356 Ha). However, after multiple experiments with different versions so far, in most cases, I couldn't obtain the energy of -76.438 Ha reported in the literature for the H₂O system. I could only get -76.434 Ha. Only the psiformer model in an early version yielded the result of -76.438 Ha.

# import os

# os.environ['CUDA_VISIBLE_DEVICES'] = '0'  # 设置使用 GPU 0
from ferminet import base_config
from ferminet import train
import os
import jax
from absl import logging
import yaml

os.environ['NVIDIA_TF32_OVERRIDE']="0"
# jax.config.update("jax_enable_x64", False)
os.environ['XLA_PYTHON_CLIENT_PREALLOCATE'] = 'false'
os.environ['XLA_PYTHON_CLIENT_MEM_FRACTION'] = '0.8'

# Optional, for also printing training progress to STDOUT.
# If running a script, you can also just use the --alsologtostderr flag.
# logging.get_absl_handler().python_handler.stream = sys.stdout
logging.set_verbosity(logging.INFO)

from pyscf import gto
LiH_mol = gto.Mole()
LiH_mol.build(
    atom=f'Li 0 0 0; H 1.595 0 0',
    basis={'Li': 'ccpvdz', 'H': 'ccpvdz'},
    spin=0)

BeH_mol = gto.Mole()
BeH_mol.build(
    atom=f'Be 0 0 0; H 1.326903 0 0',
    basis={'Be': 'ccpvdz', 'H': 'ccpvdz'},
    # ecp={'Be': 'ccecp'},
    spin=1)

BH_mol = gto.Mole()
BH_mol.build(
    atom=f'B 0 0 0; H 1.2324 0 0',
    basis={'B': 'ccpvdz', 'H': 'ccpvdz'},
    # basis={'B': '6-31g', 'H': '6-31g'},
    spin=0)

H2O_mol = gto.Mole()
H2O_mol.build(
    atom = 'O 0.00000000 0.00000000 -0.13209669; H 0.00000000 1.43152878 0.97970006; H 0.00000000 -1.43152878 0.97970006',
    basis={'O': 'ccpvdz', 'H': 'ccpvdz'},
    unit='bohr',
    spin=0)

cfg = base_config.default()
cfg.system.pyscf_mol = H2O_mol

# Set training parameters
# cfg.optim.laplacian = 'folx'
# cfg.optim.lr.rate=0.05
cfg.debug.check_nan = True
cfg.batch_size = 4096
cfg.optim.iterations = 200000
cfg.pretrain.iterations = 10000
cfg.network.network_type = f'ferminet'
cfg.log.save_path = '../GD_test/'+'H2O_ori_new2_f'

train.train(cfg)
